version = 1
SPDX-PackageName = "Gardener diki"
SPDX-PackageSupplier = "The Gardener project <gardener@googlegroups.com>"
SPDX-PackageDownloadLocation = "https://github.com/gardener/diki"

[[annotations]]
path = [".github/**", ".gitignore", ".golangci.yaml", "example/**", "CODEOWNERS", "VERSION", "go.mod", "go.sum", "tailwind.config.js", "pkg/report/templates/html/input.css", "pkg/report/templates/html/difference_report.html", "pkg/report/templates/html/merged_report.html", "pkg/report/templates/html/report.html"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2024 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2024 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["pkg/report/templates/html/_styles.tpl", "pkg/report/templates/html/output.css"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) Tailwind Labs, Inc. (https://tailwindcss.com)"
SPDX-License-Identifier = "MIT"
